/**
 * The Open Artifacts brand mark. Both exports read from apps/web/public/brand/, regenerated by
 * scripts/gen-brand-assets.sh from assets/brand/open-artifacts-logo.png — edit the source art and
 * re-run that script rather than touching the PNGs here directly.
 */

/** Ring monogram only, no wordmark — used small (sidebar rail, mobile header) where the full
 * lockup's wordmark wouldn't fit. Colorful enough to read the same on both themes. */
export function LogoMark({ size = 20, className }: { size?: number; className?: string }) {
  return <img src="/brand/logo-mark.png" width={size} height={size} alt="" className={className} />;
}

/**
 * Full lockup (ring + "Open Artifacts Project" wordmark), for the unauthenticated shell
 * (login/register). The wordmark is a flat dark navy in the source art and unreadable on the
 * dark theme, so the image itself swaps per theme via the --oa-logo-lockup token in styles.css
 * (three-state: light / dark / system — see the token's comment there for why that can't be a
 * `dark:` class).
 */
export function LogoLockup({ className }: { className?: string }) {
  return (
    <div
      role="img"
      aria-label="Open Artifacts"
      className={`bg-[image:var(--oa-logo-lockup)] bg-contain bg-center bg-no-repeat ${className ?? ""}`}
    />
  );
}
